---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.92.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: docker/cli@v20.10.17
- name: docker/compose@v2.22.0
- name: xxxserxxx/gotop@v4.2.0
- name: Aloxaf/silicon@v0.5.1

