---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.32.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: junegunn/fzf@0.42.0
- name: x-motemen/ghq@v1.4.2
- name: kubernetes/kubectl
  version: v1.24.3
- name: neovim/neovim@v0.9.1
- name: grafana/k6@v0.45.0
- name: stedolan/jq@jq-1.6
- name: golang/go@go1.20.6
- name: kubernetes-sigs/kind@v0.20.0
- name: kubernetes-sigs/krew@v0.4.4
- name: hashicorp/terraform@v1.5.4
- name: docker/cli@v20.10.17
- name: abiosoft/colima@v0.5.5
- name: lima-vm/lima@v0.16.0
- name: docker/compose@v2.20.2
- name: helm/helm@v3.12.2
- name: roboll/helmfile@v0.144.0
- name: BurntSushi/ripgrep@13.0.0
- name: sharkdp/fd@v8.7.0
- name: golang-migrate/migrate@v4.16.2
- name: mozilla/sops@v3.7.3
- name: sharkdp/bat@v0.23.0
- name: xxxserxxx/gotop@v4.2.0
- name: nektos/act@v0.2.49
- name: aquasecurity/trivy@v0.43.1
- name: sachaos/viddy@v0.3.6
- name: Aloxaf/silicon@v0.5.1
- name: cli/cli@v2.32.1
- name: starship/starship@v1.16.0

