tap "aquaproj/aqua"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "wez/wezterm"
brew "asdf"
brew "ffmpeg"
brew "fish"
brew "git"
brew "gnupg"
brew "qemu"
brew "tree-sitter"
brew "ttyd"
brew "wget"
brew "aquaproj/aqua/aqua"
cask "1password"
cask "brave-browser"
cask "discord"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "google-drive"
cask "slack"
cask "vlc"
cask "wezterm-nightly"
if OS.mac?
  tap "gromgit/fuse"
  brew "mas"
  brew "gromgit/fuse/sshfs-mac"
  cask "macfuse"
  mas "Kindle", id: 405399194
  mas "LINE", id: 539883307
  mas "Magnet", id: 441258766
end
