tap "aquaproj/aqua"
tap "gromgit/fuse"
tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "wez/wezterm"
brew "curl"
brew "git"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "mas"
brew "mise"
brew "sheldon"
brew "aquaproj/aqua/aqua"
brew "gromgit/fuse/sshfs-mac"
cask "1password"
cask "android-file-transfer"
cask "android-studio"
cask "brave-browser"
cask "discord"
cask "fig"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "macfuse"
cask "obs"
cask "obs-virtualcam"
cask "opal-composer"
cask "slack"
cask "wezterm-nightly"
cask "zoom"
mas "Hidden Bar", id: 1452453066
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Skitch", id: 425955336
mas "Xcode", id: 497799835
