brew "chezmoi"
brew "curl"
brew "git"
brew "unbound"
brew "gnutls"
brew "libassuan"
brew "gnupg"
brew "mas"
brew "mise"
brew "qemu"
brew "sheldon"
cask "1password"
cask "brave-browser"
cask "choosy"
cask "font-hackgen"
cask "font-hackgen-nerd"
casl "ghostty"
cask "google-drive"
cask "hammerspoon"
cask "opal-composer"
cask "session-manager-plugin"
cask "slack"
cask "spotify"
cask "zoom"
mas "Hidden Bar", id: 1452453066
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Skitch", id: 425955336
# mas "Xcode", id: 497799835  # Commented out for CI - install manually if needed
