#!/usr/bin/env bash
set -euo pipefail

LAZY_LOCK="${HOME}/.config/nvim/lazy-lock.json"
LAZY_DIR="${HOME}/.local/share/nvim/lazy"

cat <<'HEADER'
-- Auto-generated by scripts/gen-vimpin-pinned.sh from lazy-lock.json + git remotes.
-- Includes lazy.nvim itself; LazyVim is intentionally pinned in lua/config/lazy.lua.
-- Each entry is a partial spec override: only `commit` is pinned, while
-- LazyVim's opts/config/keys are inherited via lazy.nvim's spec merge.
-- Update via Renovate (gr1m0h/vimpin-renovate-config) or `vimpin run --update`.
return {
HEADER

jq -r 'to_entries | sort_by(.key) | .[]
  | select(.key != "LazyVim")
  | "\(.key)\(.value.branch // "")\(.value.tag // "")\(.value.commit)"' "$LAZY_LOCK" |
awk -F$'\x01' -v lazy_dir="$LAZY_DIR" '
{
  name = $1; branch = $2; tag = $3; commit = $4;
  cmd = "git -C \"" lazy_dir "/" name "\" remote get-url origin 2>/dev/null"
  cmd | getline url
  close(cmd)
  if (url == "") {
    printf "  -- SKIPPED: %s (no install dir)\n", name > "/dev/stderr"
    next
  }
  sub(/^https?:\/\/github\.com\//, "", url)
  sub(/^git@github\.com:/,         "", url)
  sub(/\.git$/,                     "", url)
  if (tag != "") {
    printf "  { \"%s\", commit = \"%s\" }, -- tag: %s\n", url, commit, tag
  } else {
    printf "  { \"%s\", commit = \"%s\" }, -- branch: %s\n", url, commit, branch
  }
}'

echo "}"
