format = """$all"""

right_format = """$git_branch $git_status"""

add_newline = false

# modules
[character]
disabled = false
error_symbol = "[✗](bold #ff5555)"
success_symbol = "[➜](bold #50fa7b)"

[cmd_duration]
disabled = false
format = "⏰[$duration]($style)"
style = "bold #f1fa8c"

[directory]
disabled = false
truncation_symbol = '…/'
style = "bold #50fa7b"

[git_branch]
disabled = false
format = "[$symbol$branch(:$remote_branch)]($style)"
style = "bold #ff79c6"

[git_status]
disabled = false
style = "bold #ffb86c"

[hostname]
disabled = false
style = "bold #bd93f9"

[username]
disabled = false
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[line_break]
disabled = false

# disabled modules
[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[fill]
disabled = true

[gcloud]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[golang]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true


[localip]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[meson]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

# default disabled
# [os]
# disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

# default disabled
# [shell]
# disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[spack]
disabled = true

# default disabled
# [status]
# disabled = true

# default disabled
# [sudo]
# disabled = true

[swift]
disabled = true

[terraform]
disabled = true

# default disabled
# [time]
# disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
