[tools]
jq = "latest"
neovim = "latest"
ghq = "latest"
act = "latest"
fzf = "latest"
ripgrep = "latest"
awscli = "latest"
lima = "latest"
colima = "latest"
gcloud = "latest"
bat = "latest"
yamlfmt = "latest"
node = "22.12.0"
flutter = "3.27.0-stable"
go = "1.23.4"
python = "3.13.2"
terraform = "1.10.2"
starship = "latest"
java = "latest"
rust = "stable"
