[tools]
jq = "latest"
neovim = "latest"
ghq = "latest"
act = "latest"
fzf = "latest"
ripgrep = "latest"
awscli = "latest"
lima = "latest"
colima = "latest"
gcloud = "latest"
bat = "latest"
yamlfmt = "latest"
node = "23.11.0"
flutter = "3.29.1-stable"
go = "1.24.1"
python = "3.13.2"
terraform = "1.11.1"
starship = "latest"
java = "latest"
rust = "1"
fd = "latest"
lazygit = "latest"
"npm:neovim" = "latest"
"npm:git-czx" = "latest"
"npm:eclint" = "latest"
"npm:typescript" = "latest"
"npm:@vercel/ncc" = "latest"
"aqua:docker/cli" = "latest"
"aqua:docker/compose" = "latest"
"aqua:xxxserxxx/gotop" = "latest"
