[tools]
node = "latest"
go = "latest"
starship = "latest"
jq = "latest"
neovim = "latest"
ghq = "latest"
act = "latest"
fzf = "latest"
ripgrep = "latest"
flutter = "latest"
awscli = "latest"
lima = "latest"
colima = "latest"
gcloud = "latest"
bat = "latest"
python = "latest"
terraform = "latest"
