[tools]
jq = "latest"
neovim = "latest"
ghq = "latest"
act = "latest"
fzf = "latest"
ripgrep = "latest"
awscli = "latest"
lima = "latest"
colima = "latest"
gcloud = "latest"
bat = "latest"
yamlfmt = "latest"
node = "22.8.0"
flutter = "3.24.3-stable"
go = "1.23.1"
python = "3.12.6"
terraform = "1.9.5"
starship = "latest"
